# prometheus.yml
global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  # Prometheus self-scrape (optional, can be removed if not needed)
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s

  # FastAPI application metrics
  - job_name: 'fastapi_app'
    static_configs:
      - targets: ['fastapi:8000']
    metrics_path: '/metrics'
    scheme: 'http'
    scrape_interval: 5s
    scrape_timeout: 5s
